# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'DKObjectC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DKObjectC

pod 'AFNetworking', '~> 4.0'
pod 'SDWebImage', '~> 5.10.0'
pod 'MJRefresh', '~> 3.5.0'
pod 'Masonry', '~> 1.1.0'

end
